### ISSUE TITLE
Stage 0 - create a repository checklist

### ISSUE THREAD

**Issue by nataliakuzan** [nataliakuzan/TPUM#1]
## Repository checklist

- [x] the task provides required feedback and has been submitted (needs grading)
- [x] the ability to clone the repository to the teacher's computer
- [x] there is README.md formatted as expected
- [x] `README.md` contains required information
- [x] build succeeded
- [x] all unit tests are green
